<?php
/**
 * @file
 * valhalla_taxonomy_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function valhalla_taxonomy_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'E',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'b44639e6-9c0b-46db-90e6-ddd63023527b',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
   $terms[] = array(
    'name' => 'A',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '40385820-cee9-4d59-81f9-a9337237bf0d',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'A',
          'format' => NULL,
          'safe_value' => 'A',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 125,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Hende der er sekretær',
          'format' => NULL,
          'safe_value' => 'Hende der er sekretær',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Socialdemokratiet',
          'format' => NULL,
          'safe_value' => 'Socialdemokratiet',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'B',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '29cc3e48-e5f3-4636-8277-b5d6092e6406',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'B',
          'format' => NULL,
          'safe_value' => 'B',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Henrik Gade',
          'format' => NULL,
          'safe_value' => 'Henrik Gade',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Det Radikale Venstre',
          'format' => NULL,
          'safe_value' => 'Det Radikale Venstre',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'C',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '334fb2cd-a44c-4f3d-a544-e1d6ed5bcff7',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'C',
          'format' => NULL,
          'safe_value' => 'C',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Suzanne Toxværd Rasmussen',
          'format' => NULL,
          'safe_value' => 'Suzanne Toxværd Rasmussen',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Konservativ Folkeparti',
          'format' => NULL,
          'safe_value' => 'Konservativ Folkeparti',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'D',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'ca1165c0-9dbf-4b74-9d8e-d726ce0d9a8d',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'F',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '44f8664e-3fa1-4973-9b68-9e110ffd0605',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'F',
          'format' => NULL,
          'safe_value' => 'F',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Lis A. Kauffmann',
          'format' => NULL,
          'safe_value' => 'Lis A. Kauffmann',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Socialistisk Folkeparti',
          'format' => NULL,
          'safe_value' => 'Socialistisk Folkeparti',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'G',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '04685f76-333f-4f52-95f6-9552f1cd89ea',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'G',
          'format' => NULL,
          'safe_value' => 'G',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'John Brædder',
          'format' => NULL,
          'safe_value' => 'John Brædder',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Nyt Guldborgsund',
          'format' => NULL,
          'safe_value' => 'Nyt Guldborgsund',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'H',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'de6df29d-4815-47b1-acf6-d165d9d1a8ad',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'I',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '14545a39-22a5-4642-9edd-82fdd4aca289',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'J',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => 'c42adc9c-c896-4207-9a44-ab98472569c7',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'K',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '9b5c6c94-e672-4ac0-abed-2f8e756e794b',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'K',
          'format' => NULL,
          'safe_value' => 'K',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Jacob Thyssen',
          'format' => NULL,
          'safe_value' => 'Jacob Thyssen',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Kristendemokraterne',
          'format' => NULL,
          'safe_value' => 'Kristendemokraterne',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'L',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => '0ef74b75-8022-48d3-b1eb-b60e51592059',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '1644c498-2437-4590-ba74-d9a017e719d7',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'N',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '62ce8073-67f7-4ee7-bc9a-492ddb23912c',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'O',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => 'e87806ee-c00a-4bac-9fcb-fe80456bcd48',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'O',
          'format' => NULL,
          'safe_value' => 'O',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Birgit Holse',
          'format' => NULL,
          'safe_value' => 'Birgit Holse',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Dansk Folkeparti',
          'format' => NULL,
          'safe_value' => 'Dansk Folkeparti',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Q',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 15,
    'uuid' => 'b0bba195-fd18-4e93-b319-78b629e0958a',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'R',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 16,
    'uuid' => '76f84a6b-619e-49fe-b741-49b95c225d98',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'S',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 17,
    'uuid' => '4f3841e0-67a6-4e39-8281-9a4f86b6155b',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'U',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 18,
    'uuid' => '4919bdf5-5d90-4b4f-9773-2943cb1a004b',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'U',
          'format' => NULL,
          'safe_value' => 'U',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Edvard Traberg',
          'format' => NULL,
          'safe_value' => 'Edvard Traberg',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Borgernes Liste Guldborgsund',
          'format' => NULL,
          'safe_value' => 'Borgernes Liste Guldborgsund',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'V',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 19,
    'uuid' => 'ff0c4dcf-9175-4aa8-89f6-fe802e63b6b3',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'V',
          'format' => NULL,
          'safe_value' => 'V',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Kaj Jørgensen',
          'format' => NULL,
          'safe_value' => 'Kaj Jørgensen',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Venstre',
          'format' => NULL,
          'safe_value' => 'Venstre',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Y',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 20,
    'uuid' => '76c1566b-0e7d-422b-8dc1-dd05ab5ccd6c',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'Z',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 21,
    'uuid' => '2d7aa1a5-2114-46d1-a3a3-64752a5aeb20',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(),
    'field_secretary' => array(),
    'field_partisek' => array(),
    'field_partinavn' => array(),
  );
  $terms[] = array(
    'name' => 'Ø',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 22,
    'uuid' => 'ef9e196c-028b-46bd-b47e-2dedf1fa3a4b',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => 'Ø',
          'format' => NULL,
          'safe_value' => 'Ø',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 94,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Christian Tastrup',
          'format' => NULL,
          'safe_value' => 'Christian Tastrup',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Enhedslisten De Rød-Grønne',
          'format' => NULL,
          'safe_value' => 'Enhedslisten De Rød-Grønne',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Adm',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 23,
    'uuid' => '9f99dd9d-8042-492a-91bd-193fa46e16c6',
    'vocabulary_machine_name' => 'partier',
    'field_logo' => array(),
    'field_bogstav' => array(
      'und' => array(
        0 => array(
          'value' => '@',
          'format' => NULL,
          'safe_value' => '@',
        ),
      ),
    ),
    'field_secretary' => array(
      'und' => array(
        0 => array(
          'uid' => 0,
        ),
      ),
    ),
    'field_partisek' => array(
      'und' => array(
        0 => array(
          'value' => 'Jesper Nikolajsen',
          'format' => NULL,
          'safe_value' => 'Jesper Nikolajsen',
        ),
      ),
    ),
    'field_partinavn' => array(
      'und' => array(
        0 => array(
          'value' => 'Administrative medarbejdere',
          'format' => NULL,
          'safe_value' => 'Administrative medarbejdere',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Folketingsvalg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '03abb9e0-7e12-488d-a06f-876cfc9536fd',
    'vocabulary_machine_name' => 'valgtype',
  );
  $terms[] = array(
    'name' => 'Kommunalvalg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '11d7a260-a17f-4abd-b1d3-4668185039b3',
    'vocabulary_machine_name' => 'valgtype',
  );
  $terms[] = array(
    'name' => 'EU parlamentsvalg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c9b4b2be-5650-476a-8675-7ad8db3802b0',
    'vocabulary_machine_name' => 'valgtype',
  );
  $terms[] = array(
    'name' => 'Regionsvalg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'df260bbe-069f-43a2-8b41-5ac844a5929f',
    'vocabulary_machine_name' => 'valgtype',
  );
   $terms[] = array(
    'name' => '8:00',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '1208149e-cca2-4e99-b956-63d4cd9e4726',
    'vocabulary_machine_name' => 'volonteers_meeting_time',
  );
  $terms[] = array(
    'name' => '16:00',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '1',
    'uuid' => '5f7f96a3-5a58-415c-a73d-39673063bfeb',
    'vocabulary_machine_name' => 'volonteers_meeting_time',
  );
  $terms[] = array(
    'name' => '19:30',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '2',
    'uuid' => 'a3732e6b-c8b7-47ec-8f0c-5344a8f28fd3',
    'vocabulary_machine_name' => 'volonteers_meeting_time',
  );
  return $terms;
}
