<?php

/*
 * @author Juulia Devadze <juulia@bellcom.ee>
 * @copyright Bellcom Open Source aps.
 */

function valhalla_settings_menu() {
  $items['admin/valhalla/settings'] = array(
      'title' => 'Settings',
      'description' => 'Lock polling station data.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('valhalla_admin_settings_form'),
      'access arguments' => array('administer valhalla'),
      'type' => MENU_LOCAL_TASK,
      'weight' => -3,
  );
  return $items;
}

function valhalla_admin_settings_form($form, &$form_state) {
  $form['valhalla_settings_polling_station_lock'] = array(
      '#type' => 'checkbox',
      '#title' => 'Lås valgsteds opsætningen',
      '#default_value' => variable_get('valhalla_settings_polling_station_lock', FALSE),
  );

  return system_settings_form($form);
}

function valhalla_settings_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'user_profile_form'){
    global $user;
    $form['field_polling_station']['#disabled'] = TRUE;
    if(in_array('administrator', $user->roles) ){
      $form['field_polling_station']['#disabled'] = FALSE;
    }
  }

  if (variable_get('valhalla_settings_polling_station_lock', FALSE)) {
    _valhalla_settings_lock_field($form, $form_state);
  }
}

function _valhalla_settings_lock_field(&$form, &$form_state) {
  $locked_fields = array('field_venue_teams', 'field_venue_team_members');
  foreach ($locked_fields as $field) {
    $lang = $form[$field]['#language'];
    $form[$field][$lang][0]['value']['#disabled'] = TRUE;
  }

  $roles = array();
  $res = db_select('node', 'n')
          ->distinct()
          ->fields('n', array('nid', 'title'))
          ->condition('n.type', 'roles')
          ->execute();

  while ($rec = $res->fetchAssoc()) {
    $roles[$rec['nid']] = $rec['title'];
  }
  $lang = $form['field_volunteers_pr_party_1']['#language'];
  //fields count 
  $field_volunteers_pr_party_1_count = count($form_state['node']->field_volunteers_pr_party_1[$lang]);

  for ($i = 0; $i < $field_volunteers_pr_party_1_count; $i++) {
    foreach ($roles as $role_id => $role) {
      $form['field_volunteers_pr_party_1'][$lang][$i]["field_role_n" . $role_id][$lang][0]['number_vo']['#disabled'] = TRUE;
      $form['field_volunteers_pr_party_1'][$lang][$i]["field_role_n" . $role_id][$lang][0]['meeting_time']['#disabled'] = TRUE;
    }
    $form['field_volunteers_pr_party_1'][$lang][$i]['remove_button']['#access'] = FALSE;
    $form['field_volunteers_pr_party_1'][$lang][$i]['field_party_list'][$lang][0]['party_list']['#disabled'] = TRUE;
  }
  $form['field_volunteers_pr_party_1'][$lang]['add_more']['#access'] = FALSE;
}
?>

