<?php

function valhalla_lists_menu(){
  $items = array();

  $items['valhalla-lists'] = array(
    'title' => 'Valghalla Lister',
    'page callback' => 'valhalla_lists_page',
    'access callback' => array('user_is_logged_in'),
  );

  return $items;
}

function valhalla_lists_page(){
  return '
<ul>
  <li><a href="/allevores">Alle tilforordnede</a></li>
  <li><a href="/mangler-svar">Tilforordnede der ikke har svaret</a></li>
  <li><a href="/valgstederU">Valgstyrere og tilforordnede</a></li>
  <li><a href="/valgsteder">Kvitteringslister for di&aelig;ter</a></li>
  <li><a href="/parti-oversigt">Parti oversigt</a></li>
  <li><a href="/valhalla_lists/frivillige-uden-email">Uden email</a></li>
  <li><a href="/valhalla_lists/beskeder">Beskeder</a></li>
  <li><a href="/valhalla_lists/valghalla-export.csv">Export: CSV</a></li>
  <li><a href="/valhalla_lists/valghalla.xls">Export: XLS</a></li>
  <li><a href="/valhalla_lists/valgstederm">Valgsteder m. CPR nummer</a></li>
</ul>
';

}
