<?php

function valhalla_lists_menu(){
  $items = array();

  $items['valhalla-lists'] = array(
    'title' => t('Valghalla Lists'),
    'page callback' => 'valhalla_lists_page',
    'access arguments' => user_is_logged_in(),
  );

  return $items;
}

function valhalla_lists_page(){
  return '
<ul>
  <li><a href="/allevores">Alle tilforordnede</a></li>
  <li><a href="/mangler-svar">Tilforordnede der ikke har svaret</a></li>
  <li><a href="/valgstederU">Valgstyrere og tilforordnede</a></li>
  <li><a href="/valgsteder">Kvitteringslister for di&aelig;ter</a></li>
  <li><a href="/parti-oversigt">Parti oversigt</a></li>
  <li><a href="/beskeder">Parti oversigt</a></li>
</ul>
';

}
